#!/bin/bash
#SBATCH -p medium      
#SBATCH -t 10:00:00
#SBATCH -o /work/ws-tmp/jl789093-ZC/logs/cluster.%A.%a.%x.log


#Make conda available
eval "$(conda shell.bash hook)"
# Activate a conda environment

conda activate zc
module load miniconda3


# - run pca on with on every $3th config (shifted by $2)
# - configs are in a .csv file ($1), generated by create_args_df.py

infile=$1
id=$2
step=$3
shift 3

python get_script_args.py --input_file $infile --id $id --step $step | while read row; do
  echo $row
  eval $row
  export pca_args=$pca_args feature_args=$feature_args train_args=$train_args row_id=$row_id
  $@  
done



